default:
	clang++ -Wall -Wextra -Weffc++ -std=c++17 -g -O3 -I /opt/homebrew/Cellar/boost/1.81.0_1/include -o assembler.out main.cpp parser.cpp symboltable.cpp

test:
	clang++ -Wall -Wextra -Weffc++ -std=c++17 -g -O3 -I /opt/homebrew/Cellar/boost/1.81.0_1/include -o assembler.test.out test.cpp parser.cpp symboltable.cpp
