default:
	clang++ -Wall -Wextra -Weffc++ -std=c++17 -O3 -o assembler.out main.cpp parser.cpp symboltable.cpp

test:
	clang++ -Wall -Wextra -Weffc++ -std=c++17 -O3 -o assembler.test.out test.cpp parser.cpp symboltable.cpp
