default:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o vm_translator.exe main.cpp parser.cpp translator.cpp

test:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o vm_translator.test.exe test.cpp parser.cpp translator.cpp