default:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o main.exe main.cpp parser.cpp translator.cpp

test:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o test.exe test.cpp parser.cpp translator.cpp