default:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o main.exe main.cpp parser.cpp symboltable.cpp

parser-test:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o parser.test.exe parser.test.cpp parser.cpp symboltable.cpp