default:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o assembler.exe main.cpp parser.cpp symboltable.cpp

test:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o assembler.test.exe test.cpp parser.cpp symboltable.cpp