default:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o compiler.exe main.cpp fs_utils.cpp

test:
	g++ -Wall -Wextra -Weffc++ -static -std=c++17 -O3 -o compiler.test.exe test.cpp fs_utils.cpp

.PHONY: test