default:
	clang++ -Wall -Wextra -std=c++17 -g -O3 -I /opt/homebrew/Cellar/boost/1.81.0_1/include -o vm_translator.out main.cpp parser.cpp translator.cpp

test:
	clang++ -Wall -Wextra -std=c++17 -g -O3 -I /opt/homebrew/Cellar/boost/1.81.0_1/include -o vm_translator.test.out test.cpp parser.cpp translator.cpp